version: "3.9" 
        
services:
  database_upc:  
    image: postgres
    container_name: database_upc
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=upc
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local 